sudo: true

os:
  - linux

language: generic

env:
- PY=2.7
- PY=3.6

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev
    - libopenmpi-dev
    - openmpi-bin

before_install:
- sudo apt-get update
- sudo apt-get install xxdiff 
- if [ "$PY" = "2.7" ];  then wget "https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh" -O miniconda.sh; fi
- if [ "$PY" = "3.6" ];  then wget "https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" -O miniconda.sh; fi
- chmod +x miniconda.sh;
- ./miniconda.sh -b  -p /home/travis/miniconda;
- export PATH=/home/travis/miniconda/bin:$PATH;


install:
- conda install --yes python=$PY numpy scipy nose sphinx mock swig pip;
- pip install --upgrade pip;
- pip install mpi4py;

# install pyspline
- git clone https://github.com/mdolab/pyspline.git;
- cd pyspline;
- cp config/defaults/config.LINUX_GFORTRAN.mk config/config.mk;
- make;
- export PATH=$HOME/.local/bin:$PATH;

script:
- export PYTHONPATH=$PYTHONPATH:$PWD
- cd python/reg_tests
- python run_reg_tests.py

