sudo: true

os:
  - linux

language: generic

env:
- PY=2.7


addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev
    - libopenmpi-dev
    - openmpi-bin

before_install:
- if [ "$PY" = "2.7" ];  then wget "https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh" -O miniconda.sh; fi
- if [ "$PY" = "3.6" ];  then wget "https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" -O miniconda.sh; fi
- chmod +x miniconda.sh;
- ./miniconda.sh -b  -p /home/travis/miniconda;
- export PATH=/home/travis/miniconda/bin:$PATH;


install:
- conda install --yes python=$PY numpy=1.11.2 scipy nose mock pip;

# install pyspline
- cd $HOME/build/mdolab/pyspline;
- cp config/defaults/config.LINUX_GFORTRAN.mk config/config.mk;
- make;

# add parent directory of pyspline to python path
- export PYTHONPATH=$PYTHONPATH:$HOME/build/mdolab/

script:

# run tests
- python run_reg_tests.py -nodiff

