vmImage: 'ubuntu-18.04'

variables:
  REPO_NAME: pyspline
  DOCKER_WORKING_DIR: /home/mdolabuser/repos/$REPO_NAME
  DOCKER_MOUNT_DIR: /home/mdolabuser/travis/$REPO_NAME

  DOCKER_TAG: u18-gcc-ompi-stable



jobs:
- job:
  container: mdolab/public:$DOCKER_TAG

  steps:
  - docker run -t -d --name app --mount "type=bind,src=$(pwd),target=$DOCKER_MOUNT_DIR" mdolab/public:$DOCKER_TAG /bin/bash
  # We thrown away the existing repo in Docker, and copy the new one in-place
  - docker exec -it app /bin/bash -c "rm -rf $DOCKER_WORKING_DIR && cp -r $DOCKER_MOUNT_DIR $DOCKER_WORKING_DIR"
  - docker exec -it app /bin/bash -c ". \$HOME/.bashrc_mdolab && cd $DOCKER_WORKING_DIR && cp config/defaults/config.LINUX_GFORTRAN.mk config/config.mk && make";
  - docker exec -it app /bin/bash -c ". \$HOME/.bashrc_mdolab && cd $DOCKER_WORKING_DIR && pip install ."
  - docker exec -it app /bin/bash -c ". \$HOME/.bashrc_mdolab && cd $DOCKER_WORKING_DIR && testflo . -v"
  - docker rm -f app
  workspace:
    clean: all
  