variables:
  REPO_NAME: pyspline
  HOME: /home/mdolabuser/
  DOCKER_WORKING_DIR: /home/mdolabuser/repos/$REPO_NAME
  DOCKER_MOUNT_DIR: /home/mdolabuser/travis/$REPO_NAME

  DOCKER_TAG: u18-gcc-ompi-stable

jobs:
- job:
  pool:
    vmImage: 'ubuntu-latest'
  container:
    image: mdolab/public:$(DOCKER_TAG)
  steps:
  - script: ls && ls -a /home/mdolabuser && pwd
  # - script: rm -rf $(DOCKER_WORKING_DIR) && cp -r . $(DOCKER_WORKING_DIR)
  # - script: . $(HOME)/.bashrc_mdolab && cd $(DOCKER_WORKING_DIR) && cp config/defaults/config.LINUX_GFORTRAN.mk config/config.mk && make;
  # - script: . $(HOME)/.bashrc_mdolab && cd $(DOCKER_WORKING_DIR) && pip install .
  - script: . $(HOME)/.bashrc_mdolab && cd $(DOCKER_WORKING_DIR) && testflo . -v
  # - script: docker rm -f app
  workspace:
    clean: all