name: pyspline_test

on: push

env:
  DOCKER_TAG: 'u18-gcc-ompi-latest'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
        REPO_NAME: pyspline
        DOCKER_WORKING_DIR: /home/mdolabuser/repos/pyspline
        DOCKER_MOUNT_DIR: /home/mdolabuser/travis/pyspline
    steps:
      - uses: actions/checkout@v2
      - uses: docker://mdolab/public:${{ env.DOCKER_TAG }}
      # Before install
      - run: docker run -t -d 
         --name app 
         --mount "type=bind,src=$(pwd),target=$DOCKER_MOUNT_DIR" mdolab/public:$DOCKER_TAG 
         /bin/bash
      # Install
      - run: docker exec app /bin/bash -c "rm -rf $DOCKER_WORKING_DIR && cp -r $DOCKER_MOUNT_DIR $DOCKER_WORKING_DIR"
      - run: docker exec app /bin/bash -c ". \$HOME/.bashrc_mdolab && cd $DOCKER_WORKING_DIR && cp config/defaults/config.LINUX_GFORTRAN.mk config/config.mk && make";
      - run: docker exec app /bin/bash -c ". \$HOME/.bashrc_mdolab && cd $DOCKER_WORKING_DIR && pip install ."
      # Script
      - run: docker exec app /bin/bash -c ". \$HOME/.bashrc_mdolab && cd $DOCKER_WORKING_DIR && testflo . -v"
      # After Script
      - run: docker rm -f app

